/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivateImport } from './routes/_private'

// Create Virtual Routes

const PrivateIndexLazyImport = createFileRoute('/_private/')()
const PrivateProfileLazyImport = createFileRoute('/_private/profile')()

// Create/Update Routes

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PrivateIndexLazyRoute = PrivateIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/index.lazy').then((d) => d.Route),
)

const PrivateProfileLazyRoute = PrivateProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/profile.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileLazyImport
      parentRoute: typeof PrivateImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexLazyImport
      parentRoute: typeof PrivateImport
    }
  }
}

// Create and export the route tree

interface PrivateRouteChildren {
  PrivateProfileLazyRoute: typeof PrivateProfileLazyRoute
  PrivateIndexLazyRoute: typeof PrivateIndexLazyRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateProfileLazyRoute: PrivateProfileLazyRoute,
  PrivateIndexLazyRoute: PrivateIndexLazyRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PrivateRouteWithChildren
  '/profile': typeof PrivateProfileLazyRoute
  '/': typeof PrivateIndexLazyRoute
}

export interface FileRoutesByTo {
  '/profile': typeof PrivateProfileLazyRoute
  '/': typeof PrivateIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_private': typeof PrivateRouteWithChildren
  '/_private/profile': typeof PrivateProfileLazyRoute
  '/_private/': typeof PrivateIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/profile' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/profile' | '/'
  id: '__root__' | '/_private' | '/_private/profile' | '/_private/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_private"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/profile",
        "/_private/"
      ]
    },
    "/_private/profile": {
      "filePath": "_private/profile.lazy.tsx",
      "parent": "/_private"
    },
    "/_private/": {
      "filePath": "_private/index.lazy.tsx",
      "parent": "/_private"
    }
  }
}
ROUTE_MANIFEST_END */
